# Generated by Django 6.0.3 on 2026-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='plants/')),
                ('category', models.CharField(choices=[('tree', 'Tree'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('flower', 'Flower'), ('herb', 'Herb')], max_length=50)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
