# Generated by Django 5.2.13 on 2026-04-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('flag', models.ImageField(upload_to='flags/')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plants.plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants.country'),
        ),
    ]
