# Generated by Django 6.0.4 on 2026-04-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='media/image/default.jpg', upload_to='image/'),
        ),
    ]
