# Generated by Django 6.0.4 on 2026-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='plant',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(choices=[('full_sun', 'Full Sun'), ('partial', 'Partial Shade'), ('shade', 'Full Shade')], default='full_sun', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_needs',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
