# Generated by Django 6.0.4 on 2026-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(upload_to='flags/')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(related_name='plants', to='plants.country'),
        ),
    ]
