# Generated by Django 6.0.4 on 2026-04-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_rename_plants_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('herb', 'Herb'), ('flowering', 'Flowering'), ('succulent', 'Succulent'), ('houseplant', 'Houseplant'), ('medicinal', 'Medicinal'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('tree', 'Tree'), ('indoor', 'Indoor')], verbose_name=1024),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=1024)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
