# Generated by Django 6.0.3 on 2026-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
    ]
