# Generated by Django 5.2.13 on 2026-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_country_remove_comment_rating_alter_comment_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
