# Generated by Django 6.0.4 on 2026-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Flower', 'Flower'), ('Tree', 'Tree'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Herb', 'Herb')], max_length=50),
        ),
    ]
