# Generated by Django 6.0.4 on 2026-04-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='sunlight',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='water_needs',
        ),
    ]
