# Generated by Django 5.2.13 on 2026-04-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_country_flag_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_comments', to='plants.plant'),
        ),
    ]
