# Generated by Django 6.0.3 on 2026-04-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_nativeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
                ('flag', models.ImageField(default='images/world.png', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='NativeTo',
        ),
    ]
