# Generated by Django 6.0.3 on 2026-04-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Origin',
        ),
        migrations.RenameField(
            model_name='origin',
            old_name='name',
            new_name='place',
        ),
    ]
