# Generated by Django 6.0.3 on 2026-04-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_rename_category_origin_rename_name_origin_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Origin',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='place',
            new_name='name',
        ),
    ]
