# Generated by Django 6.0.3 on 2026-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_country_delete_nativeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='plants.country'),
        ),
    ]
