# Generated by Django 6.0.4 on 2026-04-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_country_plant_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name_plant',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
