# Generated by Django 6.0.3 on 2026-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plant_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(default=12, upload_to='flags/'),
            preserve_default=False,
        ),
    ]
