# Generated by Django 6.0.4 on 2026-04-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_name_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name_plant',
            field=models.CharField(max_length=1000),
        ),
    ]
