# Generated by Django 5.2.13 on 2026-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_comment_name_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/default.webp', upload_to='images/'),
        ),
    ]
