# Generated by Django 6.0.3 on 2026-04-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
