# Generated by Django 6.0.4 on 2026-04-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
