# Generated by Django 6.0.4 on 2026-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Herb', 'Herb'), ('Flower', 'Flower'), ('Tree', 'Tree'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(related_name='plants', to='plants.country'),
        ),
    ]
