# Generated by Django 6.0.4 on 2026-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/plant_default.jpg', upload_to='images/'),
        ),
    ]
