# Generated by Django 6.0.4 on 2026-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(default='images/flags/default_flag.png', upload_to='images/flags/')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(related_name='plants', to='flora.country'),
        ),
    ]
