# Generated by Django 6.0.4 on 2026-04-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0004_country_plant_countries'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publishers.publisher'),
        ),
    ]
