# Generated by Django 6.0.4 on 2026-04-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0005_plant_publisher'),
        ('publishers', '0002_publisher_email_publisher_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/plant_default.jpg', upload_to='plants/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishers.publisher'),
        ),
    ]
