# Generated by Django 6.0.4 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_country_alter_plant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='xx', max_length=2),
            preserve_default=False,
        ),
    ]
