# Generated by Django 6.0.4 on 2026-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_country_flag_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='xx', upload_to='countries/'),
            preserve_default=False,
        ),
    ]
