# Generated by Django 6.0.3 on 2026-04-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
