# Generated by Django 6.0.3 on 2026-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_commint_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
