# Generated by Django 6.0.3 on 2026-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Country',
        ),
        migrations.AddField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(to='plants.country'),
        ),
    ]
