# Generated by Django 6.0.3 on 2026-04-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_rename_category_country_plant_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='categories',
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
