# Generated by Django 6.0.3 on 2026-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_remove_plant_categories_country_flag_plant_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='countries/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(related_name='plants', to='plants.country'),
        ),
    ]
