# Generated by Django 6.0.3 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_country_flag_alter_plant_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
    ]
