# Generated by Django 6.0.3 on 2026-04-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='countries',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
