# Generated by Django 6.0.3 on 2026-04-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_country_plant_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
