# Generated by Django 6.0.3 on 2026-04-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_alter_country_options_remove_comment_name_and_more'),
        ('plants', '0015_create_comment_table'),
    ]

    operations = [
    ]
