# Generated by Django 6.0.4 on 2026-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('logo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('established_at', models.DateField()),
            ],
        ),
    ]
