# Generated by Django 6.0.4 on 2026-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
